### ISSUE TITLE
MapSwipe Web tutorials for all 3 project types

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/mapswipe-web#38]
## Details Here

https://notes.tools.togglecorp.com/ZIloevGQSxCHwn07MUzj3w?view

```[tasklist]
### Tasks
- [ ] #37
- [x] Add tutorials for Find project type
- [x] Add tutorials for Compare project type
- [x] Add tutorials for Validate project type
```

**Comment by ofr1tz** [comment]
see also #13

**Comment by ofr1tz** [comment]
Completed with #39
